# Generated by Django 3.2.5 on 2021-08-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('pan', models.IntegerField()),
                ('uan', models.IntegerField()),
                ('basic_pay', models.IntegerField()),
                ('benefites', models.IntegerField()),
                ('Taxes', models.IntegerField()),
            ],
        ),
    ]
