# Generated by Django 3.2.5 on 2021-08-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_settaxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='Taxes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='settaxes',
            name='taxPercent',
            field=models.FloatField(),
        ),
    ]
